# 1. 通信与模型路径配置
hardware: 

# 选项: "openvino" 或 "tensorrt"
  backend: "openvino"
  
  serial_port: "/dev/ttyACM0" 
 # model_path: "/home/lenzmj/ws/ambition_radar/openvino_model/red.xml" 
  model_path: "/home/lenzmj/ws/ambition_radar/openvino_model/best.xml" 

# 2. 相机内参 (严格匹配你提供的标定数据)
# 这些参数直接决定了 PnP 解算出的目标距离是否准确 
camera:
  fx: 2571.733658
  fy: 2571.231411
  cx: 1444.710774
  cy: 1088.514647
  
  # 填入标定得到的畸变系数 [k1, k2, p1, p2, k3] 
  dist_coeffs: [-0.040624, 0.045286, 0.002100, -0.006427, 0.0]

# 3. 目标物理尺寸 (单位: 米)
# 针对你提到的 60mm x 65mm 目标，必须修改此处 
target: 
  width: 0.060
  height: 0.065

# 4. 实时调参参数 
params: 
  # --- 检测器部分 ---
  conf_threshold: 0.65
  
  # 图像角点平滑系数
  # 15米远距离时，检测框的轻微抖动会被放大。建议调小以获得平滑轨迹。
  det_alpha: 0.9         
  
  # --- 解算与控制部分 ---
  # 云台控制平滑系数。
  # 建议值: 0.1 ~ 0.2。值越小，激光跟随越稳，但会有滞后。 
  solve_alpha: 0.9
  
  # 判定“锁定”的角度误差范围 (度)。
  # 15米外目标很大，0.8~1.5度通常能保证激光落在 60cm 的目标范围内。
  lock_range: 0.3
        

# 5. 结构偏移配置 (单位: 米)
# 注意：这些值是相机/激光相对于云台旋转中心的物理距离
offset:
  # 请根据实际机械安装位置测量并微调
  cam_to_gimbal: [0.0001, -0.00, 0.08]
  ray_to_gimbal: [-0.00706, -0.00, 0.1065]
  
  
  
  
  
  
  
